// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	"github.com/doitintl/banias/collector/pkg/service"
	"github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	TrackEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.CollectorService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		TrackEndpoint: MakeTrackEndpoint(s),
	}
	for _, m := range mdw["Track"] {
		eps.TrackEndpoint = m(eps.TrackEndpoint)
	}

	return eps
}
